### ISSUE TITLE
PQXX_CFLAGS is undefined

### ISSUE THREAD

**Issue by alexanderlaw** [anse1/sqlsmith#19]
Shouldn't PQXX_CFLAGS be replaced with LIBPQXX_CFLAGS in Makefile.am?

**Comment by anse1** [comment]
alexanderlaw writes:

> Shouldn't PQXX_CFLAGS be replaced with LIBPQXX_CFLAGS in Makefile.am?

hmyes, I'll push a fix.  Thank you for the report.
