### ISSUE TITLE
schema.cc:6:20: fatal error: gitrev.h: No such file or directory

### ISSUE THREAD

**Issue by jwl1989** [anse1/sqlsmith#35]
when I excute "make", I get this error
schema.cc:6:20: fatal error: gitrev.h: No such file or directory

where can I find this head file ?

**Comment by anse1** [comment]
jwl writes:

> when I excute "make", I get this error
> schema.cc:6:20: fatal error: gitrev.h: No such file or directory
>
> where can I find this head file ?

it is part of all release tarballs.  When building an unreleased version
from git, git is used to generate the file.  Hard to tell what exactly
went wrong without more details about how and what exactly you are
building.

I guess I could change the Makefile to generate a dummy gitrev.h when
building an unreleased version from git with git not available.  Will
push in a jiffy. Hope that helps.

regards,
Andreas

**Comment by df7cb** [comment]
Fixed in 67687bed1a71355069d.
