### ISSUE TITLE
configure errors happened

### ISSUE THREAD

**Issue by lipeng28** [anse1/sqlsmith#45]
Hi，I am build sqlsmith in Debian 9, when I run ./configure, the following errors are encountered:

./configure: line 4445: syntax error near unexpected token `noext,mandatory'
./configure: line 4445: `  AX_CXX_COMPILE_STDCXX_17(noext,mandatory)'

Can you please advise what the problem is?

Thanks
Peng

**Comment by lipeng28** [comment]
I may install sqlsmith 1.2.1 in another ubuntu machine, I met the following problem:
./sqlsmith --verbose --target="host=/tmp port=65432 dbname=regression"
SQLsmith v1.2.1
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.65432"?

Please advise.

**Comment by df7cb** [comment]
That just means you gave it the wrong PostgreSQL socket path or port. It's either not running there, or not running at all.
