### ISSUE TITLE
cast null as ARRAY gives syntax error

### ISSUE THREAD

**Issue by pallavisontakke** [anse1/sqlsmith#5]
Issue showed up with 's' code when running SQLSmith against PostgreSQL 9.5

e.g. valid:
postgres=# select cast (null as integer ARRAY);
 int4 
------
 
(1 row)
----
invalid:
postgres=# select cast (null as ARRAY);
ERROR:  syntax error at or near "ARRAY"
LINE 1: select cast (null as ARRAY);

SQLSmith generated this query, when testing on PostgreSQL 9.5: 

Query generated by SQLSmith is:

[sqlsmith_cast_null_as_array_query.txt](https://github.com/anse1/sqlsmith/files/267401/sqlsmith_cast_null_as_array_query.txt)

**Comment by anse1** [comment]
I normally don't bother working around errors triggered due to sqlsmith's primitive type system, but I think this one deserves an exception due to it triggering a Syntax error which are hard to filter on. Maybe I can take a look at it next weekend.

Thanks for reporting!
