### ISSUE TITLE
pg_event_trigger_table_rewrite_reason() called out of context

### ISSUE THREAD

**Issue by pallavisontakke** [anse1/sqlsmith#6]
Though this issues shows up with code 'e', from PostgreSQL code and documentation, pg_event_trigger_table_rewrite_reason() can only be called in a table_rewrite event trigger function.

In SQLSmith with PostgreSQL 9.5, looks like query being generated does not have event trigger or table rewrite, however it calls this function and shows error (as expected).

Attaching query over here.
[postgresql_event_trigger_table_rewrite_reason.txt](https://github.com/anse1/sqlsmith/files/267467/postgresql_event_trigger_table_rewrite_reason.txt)

**Comment by anse1** [comment]
Ack, trigger functions should be blacklisted in schema.cc until there is some mechanism to employ them in the right context in the grammar.
