### ISSUE TITLE
hang in SQLSmith

### ISSUE THREAD

**Issue by pallavisontakke** [anse1/sqlsmith#7]
When testing SQLSmith against PostgreSQL 9.5, I found the sqlsmith process to be hanging (not proceeding for quite a while, each time I had to kill it). Also, SQLSmith sets 'statement_timeout' to 1s, so this should not have happened. At this point tested again, without giving any target database, i.e. dry-run and found even that to hang.

e.g.:

./sqlsmith --verbose --dry-run --max-queries=20 

^C
queries: 15
AST stats (avg): height = 5 nodes = 26
error rate: 0

**Comment by anse1** [comment]
The generator is known to hang when run against an empty database ↝ #4 
Was your DB empty as well?

**Comment by pallavisontakke** [comment]
yes, it was. yes, this looks like a duplicate of #4 

Is there any list of known issues/ best practices of SQLsmith, that a new user can refer to? Something to filter out the error-noise for valid syntax errors seen?

e.g. I see multiple variants of these valid syntax error issues:
-  joining on different datatypes without typecasting 
         {ERROR:  operator does not exist: text[] = oidvector}
- array_append with cast
         {ERROR:  function pg_catalog.array_append(anyarray, unknown) does not exist}
- input type unknown
         {ERROR:  could not determine polymorphic type because input has type "unknown"}

**Comment by anse1** [comment]
I do the filtering by letting my instances `--log-to` a database that has the schema from `log.sql`.
There is a trigger included that filters out errors from the table `known` and errors matching regexps in the table `known_re`.

**Comment by anse1** [comment]
I just pushed a dump of the content of my filter tables.  Some of the messages contain system-specific paths but overall the content might still be valuable starting point for filtering.
